#!/usr/bin/env python3
"""
Local SQLite Persistence Layer
==============================
Stores completed flows, alerts, and capture sessions so that
data survives program interruptions and restarts.

Tables
------
- **sessions**  — one row per start/stop cycle with global counters.
- **flows**     — one row per completed (expired or flushed) flow with
                  all 14 features + the 5-tuple identity.
- **alerts**    — one row per alert generated by the AlertEngine.

Design notes
~~~~~~~~~~~~
* WAL journal mode for safe concurrent reads while the sniffer writes.
* Batch inserts via ``executemany`` to minimise I/O during expiry sweeps.
* The DB file defaults to ``sentinel_data.db`` next to the running script.
"""

from __future__ import annotations

import os
import sqlite3
import threading
from datetime import datetime
from typing import Dict, List, Optional


# ──────────────────────────────────────────────
# Default DB path (same directory as the script)
# ──────────────────────────────────────────────

_DEFAULT_DB_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "sentinel_data.db",
)


class SentinelDB:
    """Thread-safe SQLite wrapper for SentinelAI persistence.

    Every public method acquires its own connection from a per-thread
    cache, so the object can safely be shared across the sniffer thread
    and the Flask request threads.
    """

    def __init__(self, db_path: str = _DEFAULT_DB_PATH):
        self.db_path = db_path
        self._local = threading.local()  # per-thread connection cache
        self._init_schema()
        print(f"[DB] Database ready: {self.db_path}")

    # ── connection management ──

    def _get_conn(self) -> sqlite3.Connection:
        """Return a per-thread SQLite connection (created on first use)."""
        conn = getattr(self._local, "conn", None)
        if conn is None:
            conn = sqlite3.connect(self.db_path, timeout=10)
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA synchronous=NORMAL")
            conn.execute("PRAGMA busy_timeout=5000")
            conn.row_factory = sqlite3.Row
            self._local.conn = conn
        return conn

    def close(self) -> None:
        """Close the current thread's connection (if open)."""
        conn = getattr(self._local, "conn", None)
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass
            self._local.conn = None

    # ── schema ──

    def _init_schema(self) -> None:
        conn = self._get_conn()
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS sessions (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                started_at      TEXT    NOT NULL,
                stopped_at      TEXT,
                total_packets   INTEGER DEFAULT 0,
                total_bytes     INTEGER DEFAULT 0,
                flow_count      INTEGER DEFAULT 0
            );

            CREATE TABLE IF NOT EXISTS flows (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id      INTEGER,
                captured_at     TEXT    NOT NULL,
                src_ip          TEXT    NOT NULL,
                dst_ip          TEXT    NOT NULL,
                src_port        INTEGER NOT NULL,
                dst_port        INTEGER NOT NULL,
                protocol        TEXT    NOT NULL,
                -- Temporal features
                flow_duration   REAL    DEFAULT 0,
                iat_mean        REAL    DEFAULT 0,
                iat_variance    REAL    DEFAULT 0,
                -- Volume features
                total_bytes     INTEGER DEFAULT 0,
                avg_bytes_per_pkt REAL  DEFAULT 0,
                packet_count    INTEGER DEFAULT 0,
                -- Protocol / flag features
                syn_count       INTEGER DEFAULT 0,
                ack_count       INTEGER DEFAULT 0,
                fin_count       INTEGER DEFAULT 0,
                rst_count       INTEGER DEFAULT 0,
                proto_tcp       INTEGER DEFAULT 0,
                proto_udp       INTEGER DEFAULT 0,
                proto_icmp      INTEGER DEFAULT 0,
                proto_other     INTEGER DEFAULT 0,
                FOREIGN KEY (session_id) REFERENCES sessions(id)
            );

            CREATE TABLE IF NOT EXISTS alerts (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id      INTEGER,
                timestamp       TEXT    NOT NULL,
                alert_type      TEXT    NOT NULL,
                source          TEXT,
                description     TEXT,
                FOREIGN KEY (session_id) REFERENCES sessions(id)
            );

            -- Indices for common queries
            CREATE INDEX IF NOT EXISTS idx_flows_session   ON flows(session_id);
            CREATE INDEX IF NOT EXISTS idx_flows_captured  ON flows(captured_at);
            CREATE INDEX IF NOT EXISTS idx_flows_src_ip    ON flows(src_ip);
            CREATE INDEX IF NOT EXISTS idx_flows_protocol  ON flows(protocol);
            CREATE INDEX IF NOT EXISTS idx_alerts_session  ON alerts(session_id);
            CREATE INDEX IF NOT EXISTS idx_alerts_type     ON alerts(alert_type);
        """)
        conn.commit()

    # ── sessions ──

    def create_session(self) -> int:
        """Start a new capture session. Returns the session ID."""
        conn = self._get_conn()
        cur = conn.execute(
            "INSERT INTO sessions (started_at) VALUES (?)",
            (datetime.now().isoformat(),),
        )
        conn.commit()
        session_id = cur.lastrowid
        print(f"[DB] New session created: id={session_id}")
        return session_id

    def close_session(
        self,
        session_id: int,
        total_packets: int = 0,
        total_bytes: int = 0,
        flow_count: int = 0,
    ) -> None:
        """Mark a session as finished and store final counters."""
        conn = self._get_conn()
        conn.execute(
            """UPDATE sessions
               SET stopped_at = ?, total_packets = ?, total_bytes = ?, flow_count = ?
               WHERE id = ?""",
            (datetime.now().isoformat(), total_packets, total_bytes, flow_count, session_id),
        )
        conn.commit()
        print(f"[DB] Session {session_id} closed — {total_packets} pkts, {total_bytes} bytes, {flow_count} flows saved")

    def get_sessions(self, limit: int = 20) -> List[Dict]:
        """Return the most recent capture sessions."""
        conn = self._get_conn()
        rows = conn.execute(
            "SELECT * FROM sessions ORDER BY id DESC LIMIT ?", (limit,)
        ).fetchall()
        return [dict(r) for r in rows]

    # ── flows ──

    def save_flows(self, flows: List[Dict], session_id: Optional[int] = None) -> int:
        """Batch-insert flow summaries. Returns number of rows inserted."""
        if not flows:
            return 0
        conn = self._get_conn()
        now = datetime.now().isoformat()
        rows = []
        for f in flows:
            rows.append((
                session_id,
                now,
                f.get("src_ip", ""),
                f.get("dst_ip", ""),
                f.get("src_port", 0),
                f.get("dst_port", 0),
                f.get("protocol", ""),
                f.get("flow_duration", 0),
                f.get("iat_mean", 0),
                f.get("iat_variance", 0),
                f.get("total_bytes", 0),
                f.get("avg_bytes_per_pkt", 0),
                f.get("packet_count", 0),
                f.get("syn_count", 0),
                f.get("ack_count", 0),
                f.get("fin_count", 0),
                f.get("rst_count", 0),
                f.get("proto_tcp", 0),
                f.get("proto_udp", 0),
                f.get("proto_icmp", 0),
                f.get("proto_other", 0),
            ))
        conn.executemany(
            """INSERT INTO flows (
                session_id, captured_at,
                src_ip, dst_ip, src_port, dst_port, protocol,
                flow_duration, iat_mean, iat_variance,
                total_bytes, avg_bytes_per_pkt, packet_count,
                syn_count, ack_count, fin_count, rst_count,
                proto_tcp, proto_udp, proto_icmp, proto_other
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            rows,
        )
        conn.commit()
        return len(rows)

    def get_flows(
        self,
        session_id: Optional[int] = None,
        limit: int = 200,
        offset: int = 0,
        protocol: Optional[str] = None,
        src_ip: Optional[str] = None,
    ) -> List[Dict]:
        """Query stored flows with optional filters."""
        conn = self._get_conn()
        clauses = []
        params: list = []
        if session_id is not None:
            clauses.append("session_id = ?")
            params.append(session_id)
        if protocol:
            clauses.append("protocol = ?")
            params.append(protocol)
        if src_ip:
            clauses.append("src_ip = ?")
            params.append(src_ip)

        where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
        query = f"SELECT * FROM flows {where} ORDER BY id DESC LIMIT ? OFFSET ?"
        params.extend([limit, offset])

        rows = conn.execute(query, params).fetchall()
        return [dict(r) for r in rows]

    def get_flow_count(self, session_id: Optional[int] = None) -> int:
        conn = self._get_conn()
        if session_id is not None:
            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM flows WHERE session_id = ?", (session_id,)
            ).fetchone()
        else:
            row = conn.execute("SELECT COUNT(*) as cnt FROM flows").fetchone()
        return row["cnt"] if row else 0

    # ── alerts ──

    def save_alerts(self, alerts: List[Dict], session_id: Optional[int] = None) -> int:
        """Batch-insert alerts. Returns number of rows inserted."""
        if not alerts:
            return 0
        conn = self._get_conn()
        rows = []
        for a in alerts:
            rows.append((
                session_id,
                a.get("timestamp", datetime.now().isoformat()),
                a.get("type", "unknown"),
                a.get("source", ""),
                a.get("description", ""),
            ))
        conn.executemany(
            """INSERT INTO alerts (session_id, timestamp, alert_type, source, description)
               VALUES (?,?,?,?,?)""",
            rows,
        )
        conn.commit()
        return len(rows)

    def get_alerts(
        self,
        session_id: Optional[int] = None,
        limit: int = 100,
    ) -> List[Dict]:
        conn = self._get_conn()
        if session_id is not None:
            rows = conn.execute(
                "SELECT * FROM alerts WHERE session_id = ? ORDER BY id DESC LIMIT ?",
                (session_id, limit),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM alerts ORDER BY id DESC LIMIT ?", (limit,)
            ).fetchall()
        return [dict(r) for r in rows]

    def get_alert_count(self, session_id: Optional[int] = None) -> int:
        conn = self._get_conn()
        if session_id is not None:
            row = conn.execute(
                "SELECT COUNT(*) as cnt FROM alerts WHERE session_id = ?", (session_id,)
            ).fetchone()
        else:
            row = conn.execute("SELECT COUNT(*) as cnt FROM alerts").fetchone()
        return row["cnt"] if row else 0

    # ── statistics / history ──

    def get_history_summary(self) -> Dict:
        """Return aggregate stats across all sessions."""
        conn = self._get_conn()
        sess = conn.execute(
            "SELECT COUNT(*) as cnt, COALESCE(SUM(total_packets),0) as pkts, "
            "COALESCE(SUM(total_bytes),0) as bytes FROM sessions"
        ).fetchone()
        flows = conn.execute("SELECT COUNT(*) as cnt FROM flows").fetchone()
        alerts = conn.execute("SELECT COUNT(*) as cnt FROM alerts").fetchone()

        # Top protocols across all history
        top_proto = conn.execute(
            "SELECT protocol, COUNT(*) as cnt, SUM(total_bytes) as bytes "
            "FROM flows GROUP BY protocol ORDER BY cnt DESC LIMIT 10"
        ).fetchall()

        # Top source IPs across all history
        top_src = conn.execute(
            "SELECT src_ip, COUNT(*) as cnt, SUM(total_bytes) as bytes "
            "FROM flows GROUP BY src_ip ORDER BY bytes DESC LIMIT 10"
        ).fetchall()

        # Top alert types
        top_alert_types = conn.execute(
            "SELECT alert_type, COUNT(*) as cnt "
            "FROM alerts GROUP BY alert_type ORDER BY cnt DESC LIMIT 10"
        ).fetchall()

        return {
            "total_sessions": sess["cnt"],
            "total_packets": sess["pkts"],
            "total_bytes": sess["bytes"],
            "total_bytes_mb": round(sess["bytes"] / (1024 * 1024), 2) if sess["bytes"] else 0,
            "total_flows_stored": flows["cnt"],
            "total_alerts_stored": alerts["cnt"],
            "top_protocols": [dict(r) for r in top_proto],
            "top_source_ips": [dict(r) for r in top_src],
            "top_alert_types": [dict(r) for r in top_alert_types],
        }

    def clear_all(self) -> None:
        """Delete all stored data (for reset)."""
        conn = self._get_conn()
        conn.executescript("""
            DELETE FROM alerts;
            DELETE FROM flows;
            DELETE FROM sessions;
        """)
        conn.commit()
        print("[DB] All data cleared")
